
name:Raumkulov baiel

Меня зовут Байэл Урустанбеков, я фронтенд-разработчик  в создании веб-приложений и пользовательских интерфейсов.

Навыки:
HTML/CSS:  владею, знаю семантику, адаптивную и кроссбраузерную верстку.
CSS-фреймворки: работаю с Tailwind CSS и Bootstrap для быстрой и удобной стилизации.
JavaScript:  понимаю базовый и современный синтаксис , работаю с функциями, DOM 
Фреймворки: на Vue, Next.js, Redux Toolkit, RTK Query React. Например, создавал проекты с использованием React Router и управления состоянием.
Инструменты: активно использую Git и GitHub для контроля версий, JSON Server , REST API для работы с тестовыми данными /Vite для сборки проектов.
мест. 
Опыт разработки:
Разрабатывал проекты использованием React, TypeScript, Next, JavaScript и Tailwind CSS. 
 В процессе работы создавал адаптивные пользовательские интерфейсы, настраивал маршрутизацию, интегрировал REST API и работал с управлением состоянием приложения.
Личные качества:
Постоянно развиваюсь:Ответственный
Быстро обучаюсь новым технологиям
Внимателен к деталям
Умею работать в команде
Постоянно развиваю профессиональные навыки
Цели:
Получение позиции Frontend Developer (Junior/Intern), где смогу применять свои знания React, TypeScript и современных веб-технологий, участвовать в реальных проектах и развиваться как профессиональный разработчик..


        uses: actions/deploy-pages@v4
